falcosecurity/falcosidekick

Dockerfile
Install ca-certificates and pin alpine versions to 3.8 in order to guarantee a deterministic behaviour.
With the ca-certificates you avoid errors like the following one when trying to reach Slack:
```
2018/10/09 20:39:29 [ERROR] : (Slack) Post https://hooks.slack.com/services/<redacted>: x509: certificate signed by unknown authority
```
=> fix: install ca-certificates

outputs/alertmanager.go, outputs/client_test.go, outputs/slack.go, outputs/teams.go
Falco emits events that include non-string fields (like `proc.tty`). When some outputs encountered these fields, they would re-append the previous string field because the variable was reused. This resulted in duplicated fields in the output. This PR drops the numeric fields for now and fixes the duplicated fields.
=> Don't produce duplicate entries when events have non-string fields

README.md, config.go, config_example.yaml, deploy/helm/falcosidekick/templates/deployment.yaml, deploy/helm/falcosidekick/values.yaml, outputs/slack.go, outputs/slack_test.go, types/types.go
Add a new configuration option for the Slack output, which allows users to customize the text of the Slack message in addition to the existing attachments. The current `all` and `text` options are verbose and make it hard to surface specific valuable information. Using Go templates also gives users some flexibility to do some basic string munging.
=> Add format string for Slack outputs

deploy/helm/falcosidekick/templates/deployment.yaml
/kind bug
**What this PR does / why we need it:**
Helm ENV typo fix, allows for passing the Slack Message Format options.
=> Bug: Fix Slack Message ENV on Deploy

Dockerfile
With the entry `USER falcosidekick` I get this error message in combination with
a non-root Pod Security Policy:
```
Error: container has runAsNonRoot and image has non-numeric user (falcosidekick), cannot verify user is non-root
```
=> Use numerical USER to allow usage with k8s Pod Security Policies

outputs/smtp.go
Found what I think is a small typo in the smtp output. Changed the spelling  from serveur to server.
=> updated typo in smtp logs.

main.go
According to the documentation at https://docs.datadoghq.com/api/#post-an-event
the query parameter is named `api_key`. Also tired curling a request to
datadog and got 403 just like when running falco sidekick.
=> Fix datadog api_key query parameter

.gitignore, CHANGELOG.md, README.md, config.go, config_example.yaml, main.go, outputs/datadog.go, types/types.go
Users of the Datadog EU site should be using the another host
for their API requests, see https://docs.datadoghq.com/api/#authentication
The default value of Datadog.Host is kept as the american site, so
no changes are needed for existing (american) Datadog users.
This is my first time writing Go, so feel free to edit anything that
looks out of place.
Tested locally with both env and config file
=> Add new config Datadog.Host for using the Datadog EU site

.github/PULL_REQUEST_TEMPLATE.md
/kind cleanup
NONE
As per @Issif request, it removes the `release-note` block from the PR template.
Refs https://github.com/falcosecurity/test-infra/issues/149
=> update(.github): remove release-note block from PR template

outputs/alertmanager.go
ref: #77
> /kind bug
> /kind design
> /area build
> /area config
> /area tests
> /area helm
Fixes #
=> fix, unsupported strings in alertmanager keys

outputs/alertmanager.go
with n_events* metrics, we send actual values as labels to alertmanager -> which increases cardinality and makes impossible to aggregate alerts later. 
- this PR drpps n_events (which is just delta)
- and replaces actuall values with string representation how many events in range was dropped (possibly could be done better with integer values) -> however the assumtion here is that it shall not happen at all.
=> cardinality matters, n_events labels on alertmanager

README.md
Signed-off-by: Christian Zunker <christian.zunker@codecentric.cloud>
/kind cleanup
/area helm
The varibales in the faclo helm Chart have changed, e.g.:
https://github.com/falcosecurity/charts/blob/master/falco/values.yaml#L236
Copy&Paste of the example falco config didn't work.
=> falco helm Chart variables have moved from underscores to CamelCase

README.md
/area helm
The deployment instructions for falcosidekick seem to be outdated.
Updating them and adding a reference.
=> fix: update falcosidekick deployment instructions

outputs/mattermost.go, outputs/mattermost_test.go, outputs/slack.go, types/types.go
/kind cleanup
/area outputs
- fix the stats for Mattermost which was using for another receiver.
- add some tests
- format a bit
ps. I can add tests for the other if no one is against 
None
=> fix stats for Mattermost and add tests

go.mod, outputs/alertmanager_test.go, outputs/client_test.go, outputs/datadog_test.go, outputs/influxdb_test.go, outputs/loki_test.go, outputs/mattermost_test.go, outputs/opsgenie_test.go, outputs/slack_test.go, outputs/teams_test.go
/kind cleanup
/area tests
Use testify to assert the test results to make more clean and avoid writing more code
Fixes #
=> tests: use testify to check the test results

outputs/alertmanager.go, outputs/aws.go, outputs/datadog.go, outputs/discord.go, outputs/influxdb.go, outputs/loki.go, outputs/mattermost.go, outputs/opsgenie.go, outputs/rocketchat.go, outputs/slack.go, outputs/teams.go
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area config
/area outputs
> /area tests
> /area helm
I think it better to type assert one time in the switch statement.
Fixes #
=> Refactor type assertion in output

outputs/rocketchat_test.go, types/types.go
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area config
/area outputs
> /area tests
> /area helm
I added test to make sure that the rocket chat output works as expected.
Fixes #
=> Add Rocketchat output test

handlers.go
> /kind bug
/kind design
/area build
> /area config
> /area tests
> /area helm
I refactored some HTTP handler code: 
* Use the `http.StatusBadRequest` instead of magic number `400`
* Stop sending HTTP request to `/` for `/test` endpoint
Fixes #
=> Refactor HTTP server handler

outputs/discord.go
/kind bug
> /kind design
> /area build
> /area config
/area outputs
> /area tests
> /area helm
I found that there was a bug in Discord's Prometheus output which will mess Azure Event Hubs and Discord metrics output.
Fixes #
=> Fix Discord output's Prometheus metrics

.dockerignore
> /kind bug
/kind cleanup
> /kind design
/area build
> /area config
> /area tests
> /area helm
Optimization.
We don't need `.git/`(`3.4MB`) and `img/` (`1.0MB`) in the docker image. Smaller Docker images will use fewer resources and it makes the image safer.
Fixes #
Adding to much Docker ignore files worsen the build time and I think other files(e.g. `README.md`(32KB)) does not …
=> Add .dockerignore for small Docker images

README.md, config.go, config_example.yaml, go.mod, go.sum, handlers.go, main.go, outputs/client.go, outputs/kafka.go, stats.go, types/types.go
> /kind bug
> /kind design
/kind feature
> /area build
> /area config
/area outputs
> /area tests
> /area helm
[Apache Kafka](https://kafka.apache.org/) is one of the most famous open-source distributed event streaming platform.
I use it a lot so I want falcosidekick to support. My goal is not requesting falcosidekick to support all products. But IMO, it's worth supporting Kafka.
Fixes #
This is just a suggestion so please feel free to reject.
I …
=> Support Apache Kafka output

README.md
> /kind bug
/kind cleanup
> /kind design
> /area build
/area config
> /area tests
> /area helm
It was missing in this PR → https://github.com/falcosecurity/falcosidekick/pull/127
Fixes #
=> Add missing AWS Cloud Watch Logs minimum priority description in README.md

handlers.go, main.go, outputs/constants.go, stats.go
/kind bug
> /kind design
> /area build
/area config
> /area tests
> /area helm
When `GCP` configuration was incorrect, the output was not correctly disabled, it triggered a `nil pointer dereference` error at first event and a crash of `falcosidekick`.
```
2020/11/29 19:48:44 [ERROR] : GCP - Error while base64-decoding GCP Credentials
2020/11/29 19:48:44 [INFO]  : Enabled Outputs : 
2020/11/29 19:48:44 [INFO]  : Falco Sidekick is up and listening …
```
=> fix nil pointer when gcp config is incorrect + normalize labels of stats

.circleci/config.yml, .dockerignore, CHANGELOG.md, Dockerfile, Makefile, go.mod, go.sum, outputs/client.go, outputs/kafka.go
/kind bug
/kind cleanup
/area build
/area outputs
The kafka lib we are using is a wrapper of the libkafka written in C/C++ so we need to have a special build for that.
This PR fix the build image and also add a CI job to build the image to avoid issues in the future.
Also:
- Add some items in the dockerignore
- Format a bit the imports to follow the go best practices
- Add the license in the image
Fixes #
=> Fix dockerfile to build the new kafka output

.circleci/config.yml
/kind feature
/area build
When we merge to the main branch we can push the tag `latest` of `falcosidekick` image to docker hub, for people that want to live in the edge 😄 
This is not for release, just update the `lastest` tag image.
The release thing will be in a followup pr
/assign @leogr @Issif 
Fixes #
=> ci: when merging to the main branch push the latest tag image to dockerhub

.circleci/config.yml
/kind cleanup
/area build
clean up the filters part on the circleci yaml file to avoid confusion
so in general what we want to achieve with that
- Jobs `lint` and `test` should run for **ALL branches, PRs and tags**
- Job `build-image` should run for **any branches and PR**, and **Not run for master and tags**
- Job `build-push-main` **should run only for master branch**
Fixes #
/assign @Issif
=> ci: clean filters to avoid confusion

Dockerfile, Makefile, README.md, config_example.yaml, go.mod, go.sum, handlers.go, main.go, outputs/client.go, outputs/kafka.go, types/types.go
/kind cleanup
/area outputs
- Refactor the kafka output to use another go library that does not need to have a C lib installed in the host.
- Update dockerfile to remove the lib dependency
- add missing stats
Tested, in the log below is a container that can consume messages
```console
root@kafka:/# curl -X POST localhost:2801/test
root@kafka:/# kafka-console-consumer --bootstrap-server localhost:9092 --from-beginning --topic to-do-list --property "print.key=true"
null    {"output":"This is a test from falcosidekick","priority":"Debug","rule":"Test rule","time":"2020-12-11T13:13:40Z","output_fields":null}
```
Fixes …
=> kafka: refactor kafka to use another library

.github/PULL_REQUEST_TEMPLATE.md
Signed-off-by: Leonardo Grasso <me@leonardograsso.com>
> /kind bug
> /kind design
`area/helm` label, does not apply anymore here. I'm also adding those missing labels to the repo.
> /area build
> /area config
> /area tests
> /area helm
Fixes #
=> docs(.github): removing "helm" area label

outputs/slack.go
/kind cleanup
/area outputs
slack: add missing statds/dogstastd metrics
/assign @Issif
=> slack: add missing statds/dogstastd metrics

outputs/webhook.go
/kind cleanup
/area outputs
webhook: add missing statds/dogstastd metrics
/assign @Issif
=> webhook: add missing statds/dogstastd metrics

README.md, config.go, go.mod, go.sum, handlers.go, main.go, outputs/client.go, outputs/pagerduty.go, stats.go, types/types.go
> /kind bug
> /kind design
/kind feature
> /area build
> /area config
/area outputs
> /area tests
Many company uses PagerDuty and we want to create a incident on Falco reports.
Fixes #163 
These are documents that might help you review:
* [Incident Creation API, PagerDuty Developers](https://developer.pagerduty.com/docs/rest-api-v2/incident-creation-api/)
=> Add pagerduty output support

README.md, handlers.go, main.go
> /kind bug
/kind design
> /area build
> /area config
/area outputs
> /area tests
Unify the health check endpoint with cloud native conversion. 
This endpoint is used for health checking. See the chart implementation too https://github.com/falcosecurity/charts/blob/40e45b1f1ef2f79787f1d35b5ba565b880f626de/falcosidekick/templates/deployment.yaml#L47-L58
Fixes #
Many projects in CNCF expose `/healthz` endpoint as health check endpoint. I …
=> Change `/ping` endpoint to `/healthz`

config.go, handlers.go, main.go, outputs/alertmanager.go, outputs/aws.go, outputs/datadog.go, outputs/discord.go, outputs/googlechat.go, outputs/influxdb.go, outputs/loki.go, outputs/mattermost.go, outputs/nats.go, outputs/opsgenie.go, outputs/rocketchat.go, outputs/slack.go, outputs/smtp.go, outputs/stan.go, outputs/teams.go, types/priority.go, types/priority_test.go, types/types.go
Signed-off-by: Scott Nichols <snichols@vmware.com>
/kind cleanup
I was tripping over the string compares so I made a custom json marshaler and holder for the concept of priority.
=> Add and use priority type.

outputs/client.go
/kind cleanup
In using kubernetes clients, you really should not use the Clientset struct, instead use the Interface.
=> Prefer to use kubernetes.Interface.

README.md, config_example.yaml
=> fix spelling typo in readme and example config

handlers.go, outputs/alertmanager.go, outputs/alertmanager_test.go
Use the json UseNumber() option to not decode numbers as float64 then
when creating the am payload can just call .String on the json.Number
this means that ints don't get unnecessary precision and floats
aren't cut off short.
resolves #176
/kind feature
/area outputs
=> Include numeric values from falco payloads in alertmanager alerts

.gitignore, README.md, config.go, config_example.yaml, go.mod, handlers.go, main.go, outputs/client.go, outputs/cloudevents.go, stats.go, types/types.go
/kind feature
/area outputs
Adding CloudEvents Output support, starting with PoC of only via http binary mode.
=> Adding CloudEvents output option.

config.go, handlers.go, outputs/aws.go, outputs/client.go, outputs/kafka.go
Signed-off-by: Al Stockdill-Mander <asm@uk.ibm.com>
/kind cleanup
Our build process requires no gosec issues, I have resolved them by appropriate remediation or added nosec annotations with justification.
Also fixed a couple of things the linter was complaining about.
=> resolve gosec issues or add nosec annotations

config.go
Signed-off-by: Vyacheslav Mitrofanov <unflag@ymail.com>
/kind bug
/area config
Simply removes default "http://localhost:2802" value for Webui.URL config parameter
Currently webui output starts even if there is no such intention and begins to fill logs with errors:
```
2021/02/09 16:24:49 [ERROR] : WebUI - Post "http://localhost:2802": dial tcp 127.0.0.1:2802: connect: connection refused
```
And doc looks like webui disabled by default and can be enabled by explicitly providing Webui.URL. Also currently webui cannot be disabled, because empty parameter value substituted by "http://localhost:2802".
=> set Webui.URL default address empty

README.md, config.go, config_example.yaml, main.go, outputs/webui.go, types/types.go
I've added an explicit listenaddress option in addition to listenport.
In my particular use case I'm running falcosidekick in a net=host
container and don't want it to bind to external IPs.
Also fixed a gosec complaint about json.Unmarshal in webui.go
Signed-off-by: Al Stockdill-Mander asm@uk.ibm.com
/kind cleanup
/kind feature
/area config
Special notes for your reviewer:
I've removed the "\n" from log lines around the areas I have changed as they are not required, from https://golang.org/pkg/log/ "Every log message is output on a separate line: if the message being printed does not end in a newline, the logger will add one."
Also when resolving the gosec issue with json.Unmarshal in webui.go I changed the fmt.Sprintf to .String() on the Get() as https://golang.org/pkg/expvar/#Var …
=> Add listenaddress option

config.go
/kind bug
> /kind design
> /area build
> /area config
/area outputs
> /area tests
Kafka output settings work with `Kafka.HostPort` instead of `Kafka.URL`
=> Fix: use HostPort insted of URL

outputs/smtp_templates.go
/kind bug
> /kind design
> /area build
> /area config
/area outputs
> /area tests
Since we changed the type for `Priority` field in `Falcopayload` struct from `string` to `PriorityType` (https://github.com/falcosecurity/falcosidekick/blob/3452a892e2fb68f969481e8bfe96b105835117af/types/types.go#L14), the html template for `SMTP` output is broken. 
```
2021/02/16 23:11:48 [ERROR] : SMTP - template: html:11:6: executing "html" at <eq .Priority "debug">: error …
```
=> fix html template for SMTP

config.go
/kind cleanup
/area config
This prevents this error from being printed out, which doesn't actually prevent CUSTOMFIELDS from being set properly via an environment variable
```
2021/03/03 15:36:59 [ERROR] : Error unmarshalling config : 1 error(s) decoding:
* 'Customfields' expected a map, got 'string'
```
This default also isn't actually needed since we already initialize an empty string map in the config struct. This makes the behavior of CUSTOMFIELDS the same as Webhook.CustomHeaders and CloudEvents.Extensions which don't set this default and don't have this issue.
Fixes #
=> Prevent misleading error message when setting CUSTOMFIELDS env var

config_example.yaml, outputs/mattermost.go, outputs/rocketchat.go, outputs/slack.go, outputs/teams.go
/kind bug
/area outputs
fix small issue when using outputformat as  `fields` or `text`
Fixes https://github.com/falcosecurity/falcosidekick/issues/203
=> Fix outputformat when using fields or text

handlers.go
/kind bug
/area outputs
The field names sent in the output payload as defined [here](https://falco.org/docs/rules/supported-fields/) should be `k8s.pod.name` and `k8s.ns.name` without underscores. It's causing these fields to be missing in the prometheus metrics.
Fixes #
=> Fix k8s pod and namespace labels for prometheus metrics

README.md, config.go, config_example.yaml, handlers.go, main.go, outputs/client.go, outputs/constants.go, outputs/openfaas.go, stats.go, types/types.go
<Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
> /kind bug
> /kind design
/kind feature
> /area build
> /area config
/area outputs
> /area tests
This PR adds OpenFaaS as an output module. So, we can start sending events to the OpenFaaS functions. 
Fixes #
=> openfaas output type added

README.md, config.go, config_example.yaml, outputs/client.go, outputs/kafka.go, types/types.go
/kind bug
/area outputs
If no messages to the kafka broker has been sent within `connections.max.idle.ms` set on the broker (default 10 minutes) then the connection gets closed. The existing way of setting up the kafka connection does not re-open the connection and fails with error messages like:
``` 
10.1.2.13:42642->10.2.3.4:9092: write: broken pipe
```
I also think it's an anti-pattern to explicitly set the partition number to write to, this means we cannot balance the load across multiple brokers.
---
From the kafka-go [readme](https://github.com/segmentio/kafka-go#writer-):
To produce messages to Kafka, a program may use the low-level `Conn` API, but
the …
=> Use higher level kafka Writer api instead of low level Conn api

go.mod, outputs/googlechat.go, outputs/mattermost.go, outputs/mattermost_test.go, outputs/rocketchat.go, outputs/rocketchat_test.go, outputs/slack.go, outputs/slack_test.go, outputs/utils.go
> /kind bug
> /kind design
/kind feature
> /area build
> /area config
/area outputs
> /area tests
This PR orders the fields in "chat" outputs (`Slack`, `Mattermost`, `Rocketchat`).
#223 
Fixes #
=> re-order fields for slack/rocket/mattermost + sort them alphabetically

outputs/alertmanager.go, outputs/azure.go, outputs/cloudevents.go, outputs/datadog.go, outputs/discord.go, outputs/elasticsearch.go, outputs/googlechat.go, outputs/influxdb.go, outputs/loki.go, outputs/mattermost.go, outputs/opsgenie.go, outputs/pagerduty.go, outputs/rocketchat.go, outputs/slack.go, outputs/stan.go, outputs/teams.go, outputs/webhook.go, outputs/webui.go
/kind bug
> /kind design
> /area build
> /area config
/area outputs
> /area tests
A lot of messages in logs were in double. I removed the duplication and fix some wrong prefixes.
For example, 1 event, 2 lines in logs:
```shell
2021/04/13 21:28:35 [INFO]  : WebUI - Post OK (200)
2021/04/13 21:28:35 [INFO]  : WebUI - Publish OK
```
Fixes #
=> fix duplicated log messages and some format of log prefix

README.md, config_example.yaml
Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
> /area config
We set default values for the OpenFaaS output type to help developers to remember the values that they need to set by reducing the number of parameters that should be set.
Fixes #
=> set default values for openfaas parameters

README.md, config.go, config_example.yaml, go.mod, go.sum, handlers.go, main.go, outputs/client.go, outputs/wavefront.go, stats.go, types/types.go
**What type of PR is this?** Adds initial support to send alerts as metrics to VMware Wavefront
/area outputs
This adds support for outputing alerts as metrics to Wavefront, keeping Falco tags as Wavefront tags, adding an additional severity tag for people willing to create alerts in future
=> Adds initial support to sending metric alert to wavefront

outputs/aws.go
Use previously created session to avoid using deprecated session.New()
Use session.NewSession() to allow AWS IRSA
/kind bug
> /kind design
> /area build
> /area config
/area outputs
> /area tests
Fixes #219 
=> AWS IRSA support

outputs/gcp.go, types/types.go
> /kind bug
> /kind design
/kind feature
> /area build
> /area config
/area outputs
> /area tests
This is a small PR to enable the usage of [workload identity](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity) for GCP pubsub. If no GCP credentials are passed in but the Topic and Project fields are populated it will now assume WorkloadIdentity is the intended option. I am not sure if having a flag open for "enabling" this would be better as it is more explicit but would not actually enable it.
The …
=> Add Workload Identity to GCP Output

outputs/aws.go
Signed-off-by: Kaizhe Huang <khuang@aurora.tech>
Bug fix
/kind bug
> /kind design
> /area build
> /area config
/area outputs
> /area tests
This PR is to fix issue #234 
#234 
Fixes #
=> check nil pointer before reference to SSECustomerKeyMD5

README.md, config.go, config_example.yaml, outputs/client.go, outputs/client_test.go, outputs/elasticsearch.go, outputs/gcpcloudrun.go, outputs/kubeless.go, outputs/loki.go, outputs/opsgenie.go, outputs/webhook.go, types/types.go
/kind feature
/area outputs
/area tests
Elasticsearch primarily supports Basic Authentication as the means of authenticating to the server. This PR should allow users to use HTTP Basic Authentication with Elasticsearch. There was an attempt to make it easy to apply Basic Authentication to other providers as well, though no other output providers are configured in this PR.
This PR also cleans up the Post method in client.go to force the outputs to set the headers in their own Post methods.
N/A
Previously: I'm going to get to the tests eventually. Trust me.
Now: Maybe I got to the tests? Maybe?
=> Reorg Headers, Add Basic Auth for Elasticsearch

config_example.yaml
Signed-off-by: Tom Kelley <distortedsignal@gmail.com>
/kind cleanup
Documentation?
There were two `nats` blocks in the config_example.yaml. This PR should remove one.
I think that having two blocks in YAML with the same name is an error (or my text editor is reporting that it is).
N/A
This is really low priority. Feel free to ignore.
=> Nats only needs one YAML block.

Makefile, outputs/client.go, outputs/client_test.go
Signed-off-by: Tom Kelley <distortedsignal@gmail.com>
/kind bug
/area outputs
[Somebody](https://github.com/distortedsignal/) [made a PR](https://github.com/falcosecurity/falcosidekick/pull/245) that contained a memory leak for most of the outputs in the Falcosidekick. Since the header list was never reset and the output objects are long-lived (they're not recreated for each POST), headers would populate across request boundaries. For most outputs, this would be a major problem. For the `Kubeless` output, this is a critical problem since an event-id is generated for each event/POST request.
N/A …
=> Prevent memory leak in headers.

README.md, config.go, config_example.yaml, handlers.go, main.go, outputs/client.go, outputs/constants.go, outputs/fission.go, stats.go, types/types.go
Signed-off-by: Gaurav Gahlot <gauravgahlot0107@gmail.com>
/kind feature
/area outputs
This PR adds [Fission](https://fission.io) as an output module. So, we can start sending events to the Fission functions.
Fixes #
Work in progress.
=> added fission output type

README.md, config.go, handlers.go, main.go, outputs/yandex.go, stats.go, types/types.go
- Added Yandex S3 output
- fixed GoLint error
/kind feature
> /area build
> /area config
/area outputs
> /area tests
https://github.com/falcosecurity/falcosidekick/issues/258
Fixes #
=> Yandex S3 output

README.md, config.go, config_example.yaml, go.mod, go.sum, handlers.go, main.go, outputs/kafkarest.go, stats.go, types/types.go
Signed-off-by: Engin Diri <engin.diri@mail.schwarz>
Fixes #262 
> /kind bug
> /kind design
/kind feature
> /area build
> /area config
/area outputs
> /area tests
The Kafka REST Proxy provides a RESTful interface to a Apache Kafka cluster, making it easy to produce and consume messages, view the state of the cluster, and perform administrative actions without using the native Kafka protocol or clients.
**Which issue(s) this PR fixes**:  #262 
Fixes #262 
=> Add KafkaRest as new output for Falco Sidekick

.circleci/config.yml
/kind feature
/area build
This PR adds a job to build and publish a container image to AWS public ECR registry.
NONE
We try to make OCI artifacts highly available by hosting them on different public registries like Docker Hub and AWS ECR.
=> ci: add step to push to aws ecr too

.circleci/config.yml
Signed-off-by: maxgio92 <massimiliano.giovagnoli.1992@gmail.com>
/kind bug
/area build
This PR includes the missing but required dependencies on the build and artifact publish job to AWS ECR.
NONE
The previous container image (`docker:stable`) did not include the required GNU Make.
=> ci: include required deps for build and push to ecr

.circleci/config.yml
Signed-off-by: maxgio92 <massimiliano.giovagnoli.1992@gmail.com>
/kind bug
/area build
This PR includes the missing but required dependencies on the build and artifact publish job to AWS ECR.
NONE
=> ci: add missing bash dep on push to ecr job

.circleci/config.yml, .goreleaser.yml
Signed-off-by: maxgio92 <massimiliano.giovagnoli.1992@gmail.com>
/kind bug
/area build
This PR introduces the release job steps needed to publish the OCI release images to AWS ECR.
NONE
NONE
=> ci: add steps to release oci images to aws ecr

README.md, config.go, config_example.yaml, main.go, outputs/alertmanager.go, types/types.go
Signed-off-by: Mathilde Hermet <mathildehermet94260@gmail.com>
/kind feature   
/area config   
**What this PR does / why we need it**:   
There are two versions of Alertmanager endpoint to post alerts: v1 and v2.   
Previously, this endpoint was hardcoded with v1.   
As a result, an upgrade of Alertmanager might leads to an impossible communication between Falcosidekick and Alertmanager.   
**Which issue(s) this PR fixes**:   
Fixes #280
=> Add alertmanager variable to choose the endpoint version of alertmanager api

.circleci/config.yml, .goreleaser.yml, Dockerfile, Makefile
/kind feature
/area build
- Add targets for arm/v7 and arm64 for both binaries and images
- Changed the dockerfile to use the binary we already built in the goreleaser definition, so we don't need to rebuild that again.
- added the build ci pipelines to use goreleaser to build the images as well
tested both arm and arm64 and seems to work fine
/assign  @Issif @leogr
```
• loading go mod information
• writing effective config file
• writing                   config=dist/config.yaml
• building binaries
• building                  binary=/home/circleci/project/falcosidekick/dist/falcosidekick_linux_arm_7/falcosidekick
• building …
```
=> build binaries and image for arm64 and arm

README.md, handlers.go, outputs/opsgenie.go, outputs/opsgenie_test.go
/kind cleanup
/area outputs
opsgenie: replace . with _
I've setup an opsgenie account and tested this change, seems to work fine
Fixes https://github.com/falcosecurity/falcosidekick/issues/286
=> opsgenie: replace . with _

.circleci/config.yml, .goreleaser.yml, Makefile, config.go, main.go, version.go
/kind feature
/area outputs
add version flag to falcosidekick, this will help to troubleshoot any possible community issues, because we can ask for the version that happened
```
$ docker run falcosecurity/falcosidekick:stable-amd64 --version
GitVersion:    2.24.0-17-g420e03e-dirty
GitCommit:     420e03e47c3b0e94bb901eafb5ee01786c8a537e
GitTreeState:  dirty
BuildDate:     '2021-12-05T14:58:21Z'
GoVersion:     go1.17.3
Compiler:      gc
Platform:      linux/amd64
```
it will log as well when falcosidekick starts
```
$ ./falcosidekick -c config.yaml
2021/12/05 16:06:55 [INFO]  : Falco Sidekick version: 2.24.0-11-gcefd9b8-dirty
2021/12/05 16:06:55 [INFO]  : Enabled …
```
=> add version to falcosidekick

.circleci/config.yml
/kind cleanup
/area build
we are getting this error in the circleci jobs `Too long with no output (exceeded 10m0s)` this is because the job is taking more time to build and that did not output anything during the build so circleci understand that is stuck.
increasing the no output timeout fix the issue
Fixes #
=> ci: set the no outpout timeout for the circleci jobs

README.md, config.go, config_example.yaml, handlers.go, main.go, outputs/cliq.go, outputs/cliq_test.go, stats.go, types/types.go
Signed-off-by: Antonio Verni <me.verni@gmail.com>
> /kind bug
> /kind design
/kind feature
> /area build
> /area config
/area outputs
> /area tests
This PR allows post events to [Zoho Cliq](https://www.zoho.com/cliq/)
Zoho Cliq API reference: https://www.zoho.com/cliq/help/restapi/v2/
=> Zoho Cliq output

README.md, config.go, config_example.yaml, outputs/loki.go, types/types.go
/kind feature
/area config
This change allows to add a "tenant header" in the configuration file at the
loki.tenant key.
Why :
Loki is able to differentiate logs coming from a specific tenant , but
it is needed to add a header in the configuration :
https://grafana.com/docs/loki/latest/operations/multi-tenancy/
This change does not bring any breaking changes.
Signed-off-by: Julien Godin <julien.godin@camptocamp.com>
=> feat(loki): Add tenant for loki

outputs/gcp.go
/kind bug
/area outputs
Fixes a bug in the GCP `UploadGCS` function in which the bucket writer is not properly closed, preventing the new object from being written to the remote bucket.
(one sec)
Fixes #313 
Tested locally.
Previously: new object not written post-execution.
After change: new object is written post-execution.
=> Close GCS writer on return

README.md, config.go, config_example.yaml, main.go, types/types.go
/kind deprecation
/area outputs
**Why** :
According to the documentation :
https://grafana.com/docs/loki/latest/api/#post-apiprompush
`/api/prom/push` is deprecated and is replaced by `/loki/api/v1/push`
**Any specific area of the project related to this PR?** :
standard api upgrade
This change can break older unspecified loki versions
Signed-off-by: Julien Godin <julien.godin@camptocamp.com>
=> feat(loki) : upgrade loki endpoint url

README.md, config.go, config_example.yaml, handlers.go, main.go, outputs/aws.go, stats.go, types/types.go
/kind feature
/area outputs
This PR adds [AWS Kinesis](https://aws.amazon.com/kinesis/) as an output module.
Fixes #221 
Signed-off-by: Gaurav Gahlot <gauravgahlot0107@gmail.com>
=> AWS Kinesis as an output

README.md, config.go, config_example.yaml, outputs/alertmanager.go, outputs/alertmanager_test.go, types/types.go
/kind feature
/area config
/area outputs
Allows the EndsAt alert parameter to be configured
Fixes #322
**Special notes for your reviewer**: N/A
=> Allow EndsAt field to be specified for alertmanager alerts

config.go, config_example.yaml, handlers.go, main.go, outputs/loki.go, outputs/utils.go, stats_prometheus.go
… labels for Loki for CustomFields and ExtraFields
/kind bug
> /kind design
#330 
> /area build
/area config
/area outputs
> /area tests
Fix the Panic for Prometheus when custom_fields are set
Allow to specify which fields to use as extra labels for Prometheus and Loki
Some lints
Fixes #
=> fix Panic for prometheus metrics when CustomFields are set

README.md, config.go, config_example.yaml, handlers.go, main.go, outputs/yandex.go, stats.go, types/types.go
Hello. This PR will allow using [Yandex Data Streams](https://cloud.yandex.com/en/docs/data-streams/) for output. Can it be merged, please?
=> Adding Yandex Data Streams support

README.md, config.go, config_example.yaml, handlers.go, main.go, outputs/nodered.go, stats.go, types/types.go
> /kind bug
> /kind design
/kind feature
> /area build
> /area config
/area outputs
> /area tests
Add [Node-RED](https://nodered.org/) as output
Fixes #
=> add node-red output

outputs/alertmanager.go, outputs/alertmanager_test.go
/kind bug
> /kind design
/kind feature
> /area build
> /area config
/area outputs
/area tests
This PR adds back the priority label for alertmanager outputs. Release 2.25.0 was supposed to resolve #276 and add it but priority was replaced with eventsource. 
Fixes #339
=> Adding back priority label for Alertmanager outputs

OWNERS
/kind cleanup
/area build
For https://github.com/falcosecurity/falco/issues/2115, this PR moves inactive approvers (who had very little or zero contributions over the past 6 months) from `approvers` to `emeritus_approvers` in OWNERS.
**Does this PR introduce a user-facing change?**:
=> cleanup(OWNERS): remove inactive approvers

OWNERS
Signed-off-by: Jason Dellaluce [jasondellaluce@gmail.com](mailto:jasondellaluce@gmail.com)
What type of PR is this?
/kind cleanup
Any specific area of the project related to this PR?
/area build
What this PR does / why we need it:
For https://github.com/falcosecurity/falco/issues/2115, this removes duplicates in OWNERS for members that are both in the reviewers and in the approvers or emeritus_approvers section.
Which issue(s) this PR fixes:
Special notes for your reviewer:
=> chore(OWNERS): remove duplicates in reviewers

README.md, config.go, config_example.yaml, outputs/client.go, outputs/constants.go, outputs/smtp.go, types/types.go
Signed-off-by: Lyonel Martinez <lyonel.martinez@numberly.com>
/kind feature
/area config
/area outputs
SMTP output may now use any SASL Auth mechanisms from: Plain, OAuth-Bearer, External, Anonymous or may not use any SASL Authentication. Default to Plain. 
~~Breaking change:~~
~~- The configuration for SMTP's User/Password is now in the yaml sub-object 'auth' of the SMTP configuration~~
None
~~Need some feedbacks on:~~
~~- I moved the User/password infos in the 'auth' sub-object, but if we want to avoid breaking changes, I can change the config to flatten it. WDYT ?~~
=> feat(SASL-Auth): Now SMTP output may use any SASL Auth mechanisms 

outputs/client.go, outputs/client_test.go
/kind bug
> /kind design
> /area build
> /area config
/area outputs
> /area tests
The `checkcert` setting for the outputs wasn't considered and the logic of its usage were reversed.
```
2022/07/20 10:15:41 [ERROR] : Elasticsearch - Post "https://localhost:9200/falco-2022.07.20/event": x509: certificate signed by unknown authority
```
Fixes #
=> fix missing Checkcert parameter + wrong logic with its usage

go.sum, outputs/policyreport.go
> /kind bug
> /kind design
/kind feature
> /area build
> /area config
/area outputs
> /area tests
Set the `OwnerReference` to the `Namespace` for `PolicyReports`
#331 
Fixes #
=> set ownerreference for policy reports

README.md, config.go, config_example.yaml, outputs/alertmanager.go, types/types.go
Signed-off-by: Lyonel Martinez <lyonel.martinez@numberly.com>
/kind feature
/area outputs
Now, we can add extra labels and extra annotations to the alerts send to the AlertManager Output.
Each label/annotation can have a name and a value defined by this format:
```
config:
alertmanager:
extralabels: "label1:value1, label2:value2"
extraannotations: "annotation1:value1, annotation2:value2"
```
None
We can use the same format to add extra labels with values to the Prometheus' extra-labels configuration and to the Loki one's.
=> feat(alertmanager-extra-infos): Adding extra labels or annotations the alert

README.md, config.go, config_example.yaml, outputs/client.go
… + print message body for http error 400
> /kind bug
/kind design
> /area build
> /area config
> /area tests
The Elasticsearch has been created years ago, the Elasticsearch engine changed since, and the `type` is now deprecated for a while, the value to use is `_doc`. This PR sets `_doc` as the default type for the ES docs.
The issues we got from community noticed http 400 errors without details, so the PR introduces a print of the body message …
=> Update the default type for Elasticsearch docs from 'event' to '_doc'

README.md, config.go, config_example.yaml
> /kind bug
> /kind design
/kind feature
> /area build
/area config
> /area tests
It allows to use env vars as custom fields
Fixes #
=> allow to use envvar as custom fields

outputs/policyreport.go
Signed-off-by: Frank Jogeleit <frank.jogeleit@web.de>
/kind bug
> /kind design
> /area build
> /area config
/area outputs
> /area tests
Also determine the resource name from `ka.resp.name`, if `ka.target.name` is not available.
Fixes #
=> PolicyReport: determine resource name also from ka.resp.name

README.md, config.go, config_example.yaml, main.go, outputs/influxdb.go, types/types.go
> /kind bug
> /kind design
/kind feature
> /area build
> /area config
/area outputs
> /area tests
update Influxdb output to use API Token and api/v2
Fixes #
=> update Influxdb output to use API Token and api/v2

README.md, config.go, config_example.yaml, handlers.go, main.go, outputs/zincsearch.go, stats.go, types/types.go
> /kind bug
> /kind design
/kind feature
> /area build
> /area config
/area outputs
> /area tests
This PR add [**Zincsearch**](https://docs.zincsearch.com) as new output
Fixes #
=> add Zincsearch output

outputs/smtp.go
/kind bug
> /kind design
> /area build
> /area config
/area outputs
> /area tests
Add headers to SMTP payload to avoid to trigger Antispam (Amavis)
```
Content-Type: multipart/alternative; boundary=4t74weu9byeSdJTM
Date: Mon Sep 05 11:17:34 +0000 2022
From: sender@test.com
MIME-version: 1.0
Message-ID: eRLbKi-tUeoWDSSmeho7nHjlsb9EoygIGrzH22YAsS8=@mailhog.example
Received: from localhost by mailhog.example (MailHog)
id …
```
=> add From, To and Date header in smtp payload

README.md, config.go, config_example.yaml, handlers.go, main.go, outputs/tekton.go, outputs/webhook.go, stats.go, types/types.go
> /kind bug
> /kind design
/kind feature
> /area build
> /area config
/area outputs
> /area tests
Add a dedicated output for [**Tekton**](https://tekton.dev)
Fixes #
=> tekton output

handlers.go, types/types.go
> /kind bug
> /kind design
/kind feature
> /area build
> /area config
/area outputs
> /area tests
This PR introduces a method to check the payload from Falco.
#370 
Fixes #
=> add method to check falco payload

README.md, config.go, config_example.yaml, handlers.go, main.go, outputs/client.go, outputs/spyderbat.go, stats.go, types/types.go
/kind feature
/area outputs
This PR adds Spyderbat as an output module.
Note: in order for Spyderbat to be able to use the data gathered from Falcosidekick, it needs process IDs, so my PR https://github.com/falcosecurity/falco/pull/2211 needs to be merged for this to be useful.
=> Add Spyderbat output

README.md, config.go, config_example.yaml, outputs/client.go, outputs/loki.go, types/types.go
…ed + print the body for all 40x errors
> /kind bug
> /kind design
/kind feature
> /area build
> /area config
/area outputs
> /area tests
This PR allows to set up User + API Key for Loki output, this allows to use the SaaS version of Loki, Grafana Logs.
To make easier the debugging, the response body is now printed for all 40x errors
#377 
Fixes #
=> allow to set user and api key for Loki output when Grafana Logs is used

outputs/client.go, outputs/cliq.go, outputs/elasticsearch.go, outputs/fission.go, outputs/gcpcloudrun.go, outputs/gotify.go, outputs/grafana.go, outputs/influxdb.go, outputs/kubeless.go, outputs/loki.go, outputs/nodered.go, outputs/opsgenie.go, outputs/spyderbat.go, outputs/webhook.go, outputs/zincsearch.go
A dirty fix for https://github.com/falcosecurity/falcosidekick/issues/375#issuecomment-1306253283
This addresses the short term fix, while a longer term fix will still be required.
=> Outputs dirty locking

README.md, config.go, config_example.yaml, outputs/syslog.go, types/types.go
> /kind bug
> /kind design
/kind feature
> /area build
> /area config
/area outputs
> /area tests
Support [CEF](https://learn.microsoft.com/en-us/azure/sentinel/cef-name-mapping) format for Syslog output
```
CEF:0|Falcosecurity|Falco|1.0|Falco Event|Unexpected outbound connection destination|4|uuid=f1fe1e58-6f3f-4562-bc80-aafec699b45a start=2022-11-29T15:35:01Z msg=Disallowed outbound connection destination (command=%proc.cmdline pid=%proc.pid connection=%fd.name …
```
=> add CEF format for syslog output

go.mod, go.sum, outputs/awssecuritylake.go
Closes: #389
Signed-off-by: Michael Gasch <15986659+embano1@users.noreply.github.com>
/kind bug
> /kind design
> /area build
> /area config
/area outputs
> /area tests
Improves error handling in AWS Security Lake output.
Fixes #389 
I could not test the PR as I am not very familiar with the project (I'm the maintainer of `memlog` which is used here). Would be great to get some discussion on the PR as my understanding of the Falco agent …
=> fix: Error handling in AWS Security Lake

README.md, config.go, config_example.yaml, go.mod, go.sum, handlers.go, main.go, outputs/client.go, outputs/redis.go, stats.go, types/types.go
Signed-off-by: pandyamarut [pandyamarut@gmail.com](mailto:pandyamarut@gmail.com) ([cloudDefense.ai](https://www.clouddefense.ai/))
/kind feature
/area outputs
This introduces Redis output
=> Add Redis output

.circleci/config.yml, .github/dependabot.yml, .github/workflows/build-image.yml, .github/workflows/lint.yml, .github/workflows/push-main.yml, .github/workflows/test.yml, Dockerfile, Dockerfile.dev, docker-compose.yaml, go.mod, go.sum
/kind cleanup
/kind feature
/area build
- Replace CircleCI to GitHub actions
This is the first PR to replace CircleCI to use GitHub actions, we already discussed this in slack.
This PR introduces the following things:
- add GitHub actions to test, lint, build images and push images to docker hub and aws ecr.
- the push images will happen only when we merge a PR
- During a PR we will test, lint and run goreleaser snapshot to check if everything is good.
- Also this update go to 1.20
- bump alpine image to use latest available
- and add dependabot config
There are other improvements that we can do, but will do in a follow up to make the PR smaller
also the next is to …
=> Replace circleci to use gh actions

outputs/aws.go
/kind bug
> /kind design
/kind feature
> /area build
> /area config
/area outputs
> /area tests
Remove the brackets in `MessageAtrributes` keys for `AWS SNS` output to fix:
```
2023/03/18 21:18:01 [ERROR] : AWS SNS - ParameterValueInvalid: Invalid non-alphanumeric character '#x5B' was found in the message attribute name. Can only include alphanumeric characters, hyphens, underscores, or dots.
```
Add new `DataType` for  `MessageAtrributes` keys for `AWS SNS` output:
```
"proc.pid": {
"BinaryValue": null,
"DataType": …
```
=> remove brackets in labels + add Number as DataType

handlers.go
/kind feature
/area outputs
The Sidekick doesn't give the hostname to the prom metrics leading to monitoring a simple global count of event when used outside of Kubernetes nodes.
None
=> feat(prometheus-hostname): adding hostname from playload as label of prom events metric

config.go
/kind bug
/area outputs
This fixes an error that occurs when using the TimescaleDB output:
`[ERROR] : TimescaleDB - ERROR: syntax error at or near "(" (SQLSTATE 42601)`.
Turns out because of the config typo fixed in this PR, this [line](https://github.com/falcosecurity/falcosidekick/blob/master/outputs/timescaledb.go#L45) results in an empty string table name and causes the SQL error.
Fixes #
=> fix: timescaledb hypertablename config

handlers.go, stats_prometheus.go, stats_prometheus_test.go
/kind bug
> /kind design
> /area build
> /area config
/area outputs
> /area tests
Fix cardinality issue with Prometheus metrics
```
2023/03/21 13:14:00 http: panic serving 127.0.0.1:46890: inconsistent label cardinality: expected 9 label values but got 10 in prometheus.Labels{"bkey":"BValue", "ckey":"CValue", "fd_name":"", "hostname":"falco-rkvpv", "k8s_ns_name":"falco1", "k8s_pod_name":"falco-rkvpv", "priority":"Notice", "proc_name":"bash", "rule":"Terminal shell in container", "user_name":"root"}
``` …
=> add hostname as prom label for cardinality

README.md, config.go, config_example.yaml, outputs/elasticsearch.go, outputs/grafana.go, outputs/loki.go, types/types.go
> /kind bug
> /kind design
/kind feature
> /area build
> /area config
/area outputs
> /area tests
allow to set custom headers in POST requests for loki, elasticsearch and grafana outputs
#401 
Fixes #
=> allow to set custom headers for loki, elasticsearch and grafana

README.md, config.go, config_example.yaml, handlers.go, main.go, outputs/telegram.go, outputs/telegram_test.go, stats.go, types/types.go
/kind feature
/area outputs
- introducing telegram output
- some company might use telegram for alerting system
N/A
tested on local
=> feat: introducing telegram output

outputs/awssecuritylake.go
> /kind bug
/kind design
/kind feature
> /area build
> /area config
/area outputs
> /area tests
With the upcoming GA of AWS Security Lake, the pattern for keys has changed.
Fixes #
=> update key pattern for AWS Security Lake

config.go
/kind bug
/area config
Only validate Prometheus Label **names** and Annotation **names** _instead of validating **values** as well_.
Internally, Alertmanager and Prometheus use the same data model to represent both labels and annotations,
and apply the same validation logic.
See official doc here : https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels, which mentions : 
> Label names may contain ASCII letters, numbers, as well as underscores. They must match the regex [a-zA-Z_][a-zA-Z0-9_]*. Label names beginning with __ are reserved for internal use.
> 
> Label values may contain any Unicode characters.
As a practical example, we encountered an …
=> fix: alertmanager: validate labels and annotation names only, not values

README.md, config.go, config_example.yaml, handlers.go, main.go, outputs/n8n.go, stats.go, types/types.go
> /kind bug
> /kind design
/kind feature
> /area build
> /area config
/area outputs
> /area tests
Add a new output [**n8n**](https://n8n.io/)
Fixes #
=> add n8n output

README.md, config.go, outputs/timescaledb.go, outputs/timescaledb_test.go
/kind feature
/area outputs
This PR adds support for hostname, tags, custom fields, and templated fields for the TimescaleDB output.
Fixes #
=> feat(outputs): add hostname, tags, custom, and templated fields to TimescaleDB

go.mod, go.sum, outputs/wavefront.go
/kind cleanup
/area outputs
update wavefronthq/wavefront-sdk-go to v0.12.0 and fix deprecations
/assign @Issif 
cc @rikatz 
Fixes #
=> update wavefronthq/wavefront-sdk-go to v0.12.0 and fix deprecations

README.md, config.go, config_example.yaml, handlers.go, main.go, outputs/grafana.go, stats.go, types/types.go
> /kind bug
> /kind design
/kind feature
> /area build
> /area config
/area outputs
> /area tests
Add Grafana OnCall output
Fixes #
=> add Grafana OnCall output

Makefile, README.md, config.go, config_example.yaml, outputs/aws.go, outputs/awssecuritylake.go, outputs/grafana.go, types/types.go
> /kind bug
> /kind design
/kind feature
> /area build
> /area config
/area outputs
> /area tests
Allow to set `rolearn` and `externalid` for AWS outputs
Fixes #
=> add rolearn and externalid for aws outputs

outputs/spyderbat.go
/kind bug
> /kind design
> /area build
> /area config
/area outputs
> /area tests
Spyderbat outputs are currently broken using 2.27.0
Fixes #
We have an integration we show to customers that was broken in our enviro because of this, so this fixes it.
=> fixing urls (this apparently was broken by golang-1.19 semantics)

README.md, config.go, config_example.yaml, outputs/gcp.go, types/types.go
/kind feature
/area config
/area outputs
**What this PR does / why we need it**: Adds list of key-value pairs in the config below the `pubsub` option, which will be added to all the output messages as attributes.
**Which issue(s) this PR fixes**: https://github.com/falcosecurity/falcosidekick/issues/504
Fixes #
=> Add attributes to GCP PubSub messages

outputs/spyderbat.go
/kind bug
> /kind design
> /area build
> /area config
/area outputs
> /area tests
The spyderbat output uses proc.pid and evt.time but did not validate if the fields are non-empty. 
This could lead to the sidekick process terminating and falco events getting lost. 
Fixes #
We have an integration and production environment where this problem occured, and have validated the fixes in these environments.
=> check for nil values in evt.time and proc.pid

outputs/smtp.go
Currently, SMTP output will duplicate `To:`, `From:`, `Subject:` headers and due to that services like Gmail are blocking incoming emails. For example:
/kind bug
/area outputs
=> fix SMTP output duplicate headers

README.md, config.go, config_example.yaml, outputs/alertmanager.go, outputs/alertmanager_test.go, types/types.go
/kind feature
/area config
/area outputs
Automatch the priority of a falco alert into a severity label.
There is a configuration options built to over the default map if the priority is found in this config map. Otherwise, we use the default.
The configuration checks if the indicated priority is a valid one.
None
I'll update the docs once the feature is validated and fully dev.
=> feat(severity-priority): match the priority with alertmanager severity label

README.md, config.go, config_example.yaml, outputs/kafka.go, types/types.go
> /kind bug
> /kind design
/kind feature
> /area build
> /area config
/area outputs
> /area tests
Allow to auto create kafka topic
#546 
Fixes #
=> add setting topiccreation for kafka

config.go
/kind bug
/area config
Trim spaces before check values
None
None
=> fix(alertmanager-extra): trim names and values before checking them

README.md, config_example.yaml, outputs/kafka.go
> /kind bug
> /kind design
/kind feature
> /area build
> /area config
/area outputs
> /area tests
- Support multiple Kafka bootstrap servers [the same way other producers do](https://www.elastic.co/guide/en/logstash/current/plugins-outputs-kafka.html#plugins-outputs-kafka-bootstrap_servers). This way we can fetch initial cluster metadata from a different server in case one of them is down.
- Update the documentation to explicitly state that the kafka hostport property refers to bootstrap nodes and not just to brokers. …
=> Support multiple kafka bootstrap servers

README.md, config.go, config_example.yaml, outputs/kafka.go, types/types.go
> /kind bug
> /kind design
/kind feature
> /area build
/area config
/area outputs
> /area tests
#547
Fixes #
=> allow to use tls for kafka

outputs/kafka.go
/kind bug
/area outputs
Tha Kafka TLS output doesn't pick up any root CAs right now, so enabling TLS output should always fail
_Maybe_ #547, but not sure, hence not auto-tagging
Reviewed by @Issif on Slack
=> initialise root CAs for kafka output

README.md, config.go, config_example.yaml, outputs/client.go, types/types.go
> /kind bug
> /kind design
/kind feature
> /area build
> /area config
/area outputs
> /area tests
Following #574, we'd like to be able to specify a custom CA cert on the Kafka output. This PR adds a way to specify custom CAs as a global (i.e. common to all outputs) TLS option.
For now, this feature just affects outputs that use the outputs.Client.Post() or Put() methods.
=> Add global TLS config

outputs/dynatrace.go, outputs/dynatrace_test.go
/kind bug
/area outputs
/area tests
* Fixes an issue with the Dynatrace output that let falcosidekick panic whenever one of the output fields was nil and thus not convertible to a valid string.
* Also, fixes parsing the INT64 field `span.id` as a string instead of incorrectly casting it directly.
* Adds two test cases for the Dynatrace output.
* Correctly uses the `container.image` and `k8s.ns.name` output fields of Falco.
* Renamed `k8s.pod.id` to `k8s.pod.uid` in the Dynatrace output.
=> Fix interface conversion panic due to incorrect handling of nil output fields in the Dynatrace output

main.go, outputs/client.go, outputs/client_test.go, outputs/spyderbat.go
> /kind bug
> /kind design
> /area build
> /area config
> /area tests
Fixes #
=> chore: remove refs to deprecated io/ioutil

outputs/loki.go
I believe this should be the fix for https://github.com/falcosecurity/falcosidekick/issues/646, but I'm still figuring out a way to test it locally.
=> fix(loki): fix the deadlock in Loki integration

main.go
/kind bug
/area config
The PR fixes client mTLS verification from the server when using http_output. 
N/A
Fixes #508
=> Bug: mTLS client verification fails due to missing ClientCAs configuration in server side

README.md, config_example.yaml, main.go
> /kind bug
/kind cleanup
> /kind design
> /area build
/area config
> /area tests
Fixes #
=> update logs for TLS

outputs/utils_test.go
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area config
/area tests
Adds 100% test coverage to a file previously with 0% coverage
N/A
Fixes # NA
Pleasure meeting you at Kubecon Contribfest
=> Add test for utils sorting function

outputs/mattermost.go, outputs/rocketchat.go
/kind bug
> /kind design
> /area build
> /area config
/area outputs
> /area tests
The usernames for Mattermost/Rocketchat are hardcoded. This PR changes that.
#730 
Fixes #
=> remove hard settings of the Mattermost/Rocketchat Usernames

docs/outputs/elasticsearch.md
/area config
Remove mattermost config variable which were probably cc/cl by mistake
=> fix(elasticsearch-doc): remove mattermost configuration coming from a cc/cl mistake

outputs/client.go
/kind bug
/area outputs
Fixes #761
=> feat(log_inlined_json): inline the json logs when it's possible

main.go, outputs/client.go, outputs/client_test.go, outputs/fission.go, outputs/kubeless.go, outputs/openfaas.go, outputs/quickwit.go
/kind cleanup
/area outputs
Fixes #763
=> refactor(init_client): merge InitClient and NewClient functions

config.go, config_example.yaml, docker-compose.yaml, docs/outputs/aws_s3.md, outputs/aws.go, types/types.go
Changes: 
- add AWS.S3.Endpoint configuration option
- make canned ACL configurable
- add MinIO to `docker-compose.yaml` for local testing
/kind feature
/area outputs
I tested this change against [IBM Cloud COS](https://www.ibm.com/products/cloud-object-storage) and a local [MinIO](https://min.io/) instance.
Example `config.yaml` for the local MinIO:
```yaml
aws:
region: minio
checkidentity: false
accesskeyid: xxx
secretaccesskey: xxx
s3:
bucket: falco-test
endpoint: http://minio.localhost:9000
objectcannedacl: ""
```
=> Make S3 output compatible with non-AWS S3 API-compliant endpoints

Makefile, handlers.go, outputs/alertmanager.go, outputs/alertmanager_test.go, outputs/datadog.go, outputs/datadog_test.go, outputs/discord.go, outputs/discord_test.go, outputs/googlechat.go, outputs/googlechat_test.go, outputs/loki.go, outputs/loki_test.go, outputs/mattermost.go, outputs/mattermost_test.go, outputs/pagerduty.go, outputs/rocketchat.go, outputs/rocketchat_test.go, outputs/slack.go, outputs/slack_test.go, outputs/teams.go, outputs/teams_test.go
outputs
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area config
/area outputs
> /area tests
Try to keep a consistent order for the output field and tags for messaging outputs
#800 
Fixes #
=> try to use a consistent order for the output_fields and tags for more outputs

handlers.go
> /kind bug
> /kind design
> /area build
> /area config
> /area tests
Multiple outputs fail when the length of the payload is > 4906 characters. This PR introduces a truncate of the outputs fields to max 512 characters when the global length of the payload is > 4096.
#842 
Fixes #
=> truncate output fiels with a length > 512 chars

outputs/alertmanager.go, outputs/alertmanager_test.go
/kind bug
> /kind design
> /area build
> /area config
/area outputs
> /area tests
The labels used by alertmanager need to match the regex `[a-zA-Z_][a-zA-Z0-9_]*`. 
When adding a custom rule to get the AWS session name the label passed in is `json.value[/user/extra/sessionName]` which is currently passes out to alertmanager as `json_value_/user/extra/sessionName` which doesn't work in Alertmanager as the `/` are invalid.
=> feat(alertmanager): fix labels for alertmanager

Makefile, README.md, config.go, config_example.yaml, go.mod, handlers.go, main.go, types/types.go
/kind feature
/area config
This PR introduces a new parameter `outputFieldFormat`:
* `outputFieldFormat: "<timestamp>: <priority> <output> <custom_fields> <templated_fields>"`
```
17:50:29.343280037: Warning NodePort Service Created (user=%ka.user.name service=%ka.target.name resource=%ka.target.resource ns=%ka.target.namespace ports=%ka.req.service.ports) bkey=BValue ckey=CValue dkey=bar
```
* `outputFieldFormat: "<priority> <output> <custom_fields>"`
```
Warning NodePort Service Created (user=%ka.user.name service=%ka.target.name resource=%ka.target.resource ns=%ka.target.namespace ports=%ka.req.service.ports) bkey=BValue ckey=CValue
```
* `outputFieldFormat: …
=> add outputFieldFormat parameter

.github/workflows/lint.yml, .golangci.yml, Makefile, config.go, config_example.yaml, docs/outputs/policy_report.md, handlers.go, outputs/policyreport.go, outputs/utils.go, types/types.go
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area config
/area outputs
> /area tests
The output was hard to extend or debug, I preferred to revamp it totally for readability.
#803 #804
Fixes #
=> revamp the policy reporter output

.github/workflows/build-image.yml, .github/workflows/lint.yml, .github/workflows/push-main.yml, .github/workflows/release.yml, .github/workflows/test.yml, config.go, config_example.yaml, docs/outputs/elasticsearch.md, main.go, outputs/client.go, outputs/elasticsearch.go, outputs/elasticsearch_mapping.go, outputs/grafana.go, outputs/influxdb.go, outputs/influxdb_test.go, outputs/opsgenie.go, outputs/opsgenie_test.go, outputs/redis.go, outputs/smtp.go, outputs/webui.go, types/types.go
/kind bug
> /kind design
/kind feature
> /area build
> /area config
/area outputs
> /area tests
Allow to flatten the `output_fields` (replace `.` by `_`) to avoid the conflicts of mappings.
#762 
Fixes #
=> add flattenfields + create indextemplate

docs/outputs/aws_lambda.md, docs/outputs/aws_s3.md
Follow up for #791
The current documentation lists `AWS_CHECKIDENTITY` as `AWS_checkidentity` which does not work.
=> Docs fix: Environment variables are all uppercase

outputs/client.go
/kind feature
/area outputs
This PR reuses http.Client instance for the outputs, were it was previously created per each request.
The http.Client reuse is recommended:
https://cs.opensource.google/go/go/+/refs/tags/go1.22.6:src/net/http/client.go;l=34
We are seeing 3-4x increase of throughput for Elasticsearch output in out tests.
I tried to keep the approach to the http client and the transport creation the same as before, namely logging and continuing on error, extracted some code into the function.
=> Reuse http client

config.go, go.mod, main.go, outputs/alertmanager.go, outputs/client.go, outputs/client_test.go, outputs/cliq.go, outputs/dynatrace.go, outputs/elasticsearch.go, outputs/fission.go, outputs/gcpcloudrun.go, outputs/gotify.go, outputs/grafana.go, outputs/influxdb.go, outputs/kubeless.go, outputs/loki.go, outputs/n8n.go, outputs/nodered.go, outputs/openfaas.go, outputs/openobserve.go, outputs/opsgenie.go, outputs/otlp.go, outputs/otlp_test.go, outputs/quickwit.go, outputs/spyderbat.go, outputs/sumologic.go, outputs/webhook.go, outputs/zincsearch.go, types/types.go
/kind bug
/kind cleanup
/area config
/area outputs
Multiple improvements of http outputs handling.
Addressing the following areas:
1. There is no limit on the number of outgoing http requests, which is combined with with the lack of http client reuse creates  thousands of connections to the host (the http client reuse is addresses in this previous PR https://github.com/falcosecurity/falcosidekick/pull/962). That except in the cases where some auth related http headers are set using the mutex lock that causes the requests to be limited to one at a time competing for the mutex. 
For example the Elasticsearch output is limited to one request at a time when basic auth …
=> Improve http output handling

outputs/policyreport.go
/kind bug
/area outputs
currently when a new PolicyReport is created it reuses the modified default PolicyReport and reuses already added results which leads to duplicates in different namespaces.
this change creates new pointers for each new PolicyReport
Fixes #970
=> fix: don't share same pointer for new reports

config_example.yaml, docs/outputs/elasticsearch.md, outputs/elasticsearch.go, types/types.go
/kind feature
/area outputs
Adds ```APIKey``` configuration for Elasticsearch output
```APIKey``` is a preferred way to authenticated with Elasticsearch, since users can limit it's permissions, assign the expiration, revoke, etc.
Currently user can configure it with the ```customHeaders```, for example:
```
customHeaders:
Authorization: "APIKey U1Nfd041RUJKMGlDdzFGeld0anE6aHR2Z0kwbmNUcDZITxxxxxxxxxxxx=="
```
Exposing ```APIKey``` through a dedicated configuration option would hopefully encourage and make easier for users to use APIKey instead of basic auth.
Good convenience configuration option
=> [Elasticsearch] Add APIKey configuration for Elasticsearch output

README.md, config.go, config_example.yaml, handlers.go, types/types.go
> /kind bug
> /kind design
/kind feature
> /area build
/area config
> /area tests
Allow to append on the fly `custom tags` to the payload.
#971 
Fixes #
=> allow to specify custom tags to append

docs/outputs/loki.md
Replaced the deprecated documentation about loki
/area config
Fixes #
=> :memo: Deprecated loki documentation

docs/outputs/telegram.md, outputs/telegram.go, types/types.go
> /kind bug
> /kind design
/kind feature
> /area build
> /area config
/area outputs
> /area tests
This enhancement allows for better control over message threading in Telegram.
=> feat: add message thread id in telegramPayload

handlers.go, outputs/awssecuritylake.go, outputs/policyreport.go, outputs/spyderbat.go, stats_prometheus.go, stats_prometheus_test.go
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area config
> /area tests
With its recent releases, Falco comes now out of the box with prometheus metrics, all the metrics follow the convention `falcosecurity_<project>_<metric>_<type>`. 
`project`  represents the project, it can be `falco`, `falcosidekick` (goal of this PR), `talon`, ...
This PR introduces the prefix `falcosecurity`, add `falcosidekick` as project, and the `type` as `total` (all metrics are counters for now)
To be compliant with …
=> improve the name of the prometheus metrics

Makefile
/kind feature
/area build
This PR uses GOARCH environment variable in Makefile also in the falcosidekick container image binary build. It supports builds on arm64 architecture in addition to the amd64.
In addition it add build flags to the container image as well.
Example:
```bash
docker run --rm  docker.io/falcosecurity/falcosidekick:latest --version
GitVersion:    2.29.0-71-g0f39f47-dirty
GitCommit:     0f39f47e11721722a0993690ad472887e17085a7
GitTreeState:  dirty
BuildDate:     '2024-10-15T07:59:36Z'
GoVersion:     go1.23.2
Compiler:      gc
Platform:      linux/arm64
```
=> Support multi-architecture(arm64) build

outputs/datadog.go, outputs/datadog_test.go
> /kind bug
> /kind design
/kind feature
> /area build
> /area config
> /area tests
This PR adds a "falco" source tag to events sent to Datadog. Currently, these events are only tagged according to the Falco event source, and the Datadog default "my apps"  tag, which makes targeting all falco events in datadog quite cumbersome. With an additional "falco" tag, it is now easier to filter falco events.
Before: 
After:
Fixes #1017
=> [feature] add falco as source for datadog events

config.go, docs/outputs/datadog_logs.md
/kind bug
/area outputs
- Fix Datadog Logs output documentation. Environnement variables were wrong. 
- Add checkPriority for Datadog Logs output.
=> Fix Datadog Logs documentation + add checkPriority

outputs/loki.go
/kind design
/area outputs
This PR puts the namespace and pod name as default fields in the loki output if they exist.
This is really useful to have a good setup at start and do not go into the `extraLabels` config as they are important keys to get.
Moreover, some of these labels are used by default by the [dashboard](https://github.com/falcosecurity/charts/blob/b4e6411fca3caa7771e2bec1490b2fdc24ce2b71/charts/falcosidekick/dashboards/falcosidekick-loki-dashboard.json#L286), so it would be perfect if all the deployment (loki + dashboard) is working without extra configuration needed
=> :wrench: Add NS and pod by default in loki output

config.go, config_example.yaml, docs/outputs/nats.md, docs/outputs/stan.md, outputs/nats.go, outputs/stan.go, types/types.go
> /kind bug
> /kind design
/kind feature
> /area build
> /area config
/area outputs
> /area tests
Allow the users to use a different subject for NATS/STAN messages
#1085 
Fixes #
=> allow to set a template for the nats/stan subjects

config.go
/kind bug
> /kind design
/kind feature
> /area build
> /area config
/area outputs
> /area tests
Adds `LOKI_CUSTOMHEADERS` to `http/s` requests as expected
Fixes #1108 
=> fix custom headers not added to loki output http/s requests

handlers.go
/kind bug
> /kind design
> /area build
> /area config
> /area tests
**What this PR does / why we need it**: https://github.com/falcosecurity/falcosidekick/pull/1051 updated stats_prometheus.go to replace `.` for `_`, but the code that then adds the labels to every instance did not update it, so instances where CUSTOM_FIELDS is set to use a key with `.`s leads to panics.
**Which issue(s) this PR fixes**: No Github Issue existing so far.
Fixes #
=> Update handlers to match stats_prometheus.go
