README.md
handlers.go
main.go
outputs/alertmanager.go
outputs/datadog.go
outputs/slack.go

new output : Alert Manager from Prometheus
#6

add Alert Manager as output

---

README.md
main.go
outputs/alertmanager.go
outputs/alertmanager_test.go
outputs/client.go
outputs/client_test.go
outputs/datadog.go
outputs/datadog_test.go
outputs/slack.go
outputs/slack_test.go

- unit tests for all outputs + newClient + Post methods
- Reformatting of README for following best practices
- add recover() to catch Panic if outputs are not reachable and avoid crash of daemon
- remove disabled outputs from logs, only enabled are useful
- env vars are unset if client can't be created

Add Unit Tests

---

outputs/elasticsearch.go

Added this line to be able to create monthly indices. Tested on GKE.

Updated monthly index creation process

---

deploy/helm/falcosidekick/templates/deployment.yaml

Fixes the Helm Deployment Template so that it will function.

Fix Helm Template Error

---

.github/PULL_REQUEST_TEMPLATE.md

Proposing a template for Pull Requests, the same way other falcosecurity repositories do.
This goes in the direction of providing a unified experience, governance, and workflow for contributing to falcosecurity repositories.
Signed-off-by: Leonardo Di Donato <leodidonato@gmail.com>

new: PULL_REQUEST_TEMPLATE.md

---

OWNERS

Proposing an initial OWNERS file which contains @Issif (it needs to be uppercase) and me (it needs at least 2 maintainers, other people please feel free to express interest here for approving/reviewing roles here).
Fixes #63 
```release-note
docs: OWNERS file
```

docs: OWNERS

---

OWNERS

Signed-off-by: Thomas <issif_github@gadz.org>
> /kind bug
/kind design
> /area build
/area config
> /area tests
> /area helm
Add [nibalizer](https://github.com/nibalizer) as reviewer/approver (thanks to him !)
N/A
Fixes #
More approvers means smoother PR

add nibalizer as approver/reviewer

---

CHANGELOG.md
Dockerfile
README.md
config_example.yaml
deploy/helm/falcosidekick/Chart.yaml
deploy/helm/falcosidekick/templates/deployment.yaml
deploy/helm/falcosidekick/templates/secrets.yaml
deploy/helm/falcosidekick/values.yaml

> /kind bug
> /kind design
/kind release
> /area build
> /area config
> /area tests
> /area helm
/area release
This PR is for releasing 2.14.0
N/A
Fixes #
N/A

prepare 2.14.0

---

outputs/alertmanager.go

Signed-off-by: Spencer Krum <nibz@spencerkrum.com>
/kind bug
The code had a few bugs. We should get better testing. 
Fixes #
I may be missing something here and we *dont* need this.

Repair alertmanager

---

README.md

Signed-off-by: Spencer Krum <nibz@spencerkrum.com>
/area config
Clarify docs
This is just further cleanup from #85

docs: clarify installation instructions

---

OWNERS

> /kind bug
> /kind design
> /area build
> /area config
> /area tests
> /area helm
Just proposing myself as approver/reviewer :)
Fixes #

update(OWNERS): adding myself to approvers

---

README.md
config.go
config_example.yaml
outputs/client.go
outputs/slack_test.go
types/types.go

> /kind bug
> /kind design
/kind feature
> /area build
/area config
/area outputs
/area tests
> /area helm
This PR adds possibility to set Custom Headers that will be sent with POST for `Webhook` output, it's convenient for adding Authentication Header for example.
I've also fixed unit test for Slack.
Fixes #

add Webhook.CustomHeaders + Fix Slack unit test

---

CHANGELOG.md

> /kind bug
> /kind design
/kind feature
> /area build
/area config
/area outputs
/area tests
> /area helm
We can know add customer headers for `Webhook` output. For example `Authorization: Bearer XXXX`.
@leogr has integrated `CircleCI` too.
Fixes #

prepare 2.16.0

---

CHANGELOG.md

> /kind bug
> /kind design
/kind feature
> /area build
> /area config
/area outputs
> /area tests
> /area helm
This release provides a new output : **AWS SNS** thanks to [@IanRobertson-wpe](https://github.com/IanRobertson-wpe)
#5 
Fixes #

update changelog for 2.17.0

---

.circleci/config.yml

Signed-off-by: Leonardo Grasso <me@leonardograsso.com>
Co-authored-by: Thomas Labarussias <issif+github@gadz.org>
Signed-off-by: Leonardo Grasso <me@leonardograsso.com>
> /kind bug
/kind cleanup
> /kind design
/area build
> /area config
> /area tests
> /area helm
According to https://circleci.com/docs/2.0/configuration-reference/
> CircleCI does not run workflows for tags unless you explicitly specify tag filters. Additionally, if a job requires any other jobs (directly or indirectly), you must specify …

build(.circleci): correct tags filter

---

README.md
config_example.yaml

/kind bug
> /kind design
> /area build
/area config
> /area tests
> /area helm
`gcp` is missing in `config_example.yaml`.
Fixes #

Update doc for missing configuration "gcp" 

---

.circleci/config.yml

/kind cleanup
/area build
clean a bit the circleci config
Fixes #

clean a bit the circleci config

---

README.md

/kind bug
> /kind design
> /area build
> /area config
/area outputs
> /area tests
> /area helm
Sorry, I made a human error in the previous PR → [Add Google Chat support](https://github.com/falcosecurity/falcosidekick/pull/107). 
I want to fix the document 🙇  
Fixes #

Fix wrong output figure for Google Chat

---

outputs/googlechat_test.go

/kind cleanup
/area tests
Now we are using `testify` to check the tests and we should have all test using that to follow the pattern.
Fixes #

update test to use testify

---

CHANGELOG.md
README.md

> /kind bug
> /kind design
/kind feature
/area build
> /area config
> /area tests
> /area helm
This PR prepares the next release `2.18.0` by updating the Changelog
N/A
Fixes #

update changelog for 2.18.0

---

outputs/discord.go
outputs/discord_test.go
types/types.go

> /kind bug
/kind cleanup
> /kind design
/area build
> /area config
> /area tests
> /area helm
I want to refactor and add tests for it.
With the test, I was able to refactor safely.
Fixes #

Add test for discord and refactor

---

README.md

/kind bug
> /kind design
> /area build
> /area config
/area outputs
> /area tests
> /area helm
The `/` handler should only handle `POST` HTTP method and also the same as `/test`. 
In the previous PR(Ref: https://github.com/falcosecurity/falcosidekick/pull/116), I added an HTTP method check-in these paths.
Therefore, the example quick test needs to add `-X POST` to send request with `POST` HTTP method.
Fixes #
Thank you very much in …

Fix README.md's quick test example

---

outputs/client.go

/kind bug
> /kind design
> /area build
/area config
> /area tests
> /area helm
I found a small typo 😄 
Fixes #

Chore: Fix small typo "Acces"

---

README.md

/kind bug
> /area build
> /area config
> /area tests
> /area helm
fix discord image link
NONE

fix discord image link

---

README.md
config_example.yaml

/kind bug
> /kind design
> /area build
/area config
> /area tests
> /area helm
I found this small typo  😄 
Fixes #

Fix typo Rockatchat to Rocketchat

---

CONTRIBUTING.md

> /area build
> /area config
> /area tests
> /area helm
Add initial `CONTRIBUTING.md` document
Fixes https://github.com/falcosecurity/falcosidekick/issues/96

add initial contributing document

---

.circleci/config.yml
go.mod

> /kind bug
/kind cleanup
> /kind design
/area build
> /area config
> /area tests
> /area helm
Better to use the latest version of Go.
Fixes #

Bump go version to 1.15

---

CHANGELOG.md

> /kind bug
> /kind design
/kind feature
/area build
> /area config
> /area tests
> /area helm
Prepare release `2.19.0`
N/A
Fixes #

prepare changelog for 2.19.0

---

Makefile
README.md

readme: update development part
/assign @Issif 
Fixes #

readme: update development part

---

outputs/alertmanager.go

/kind cleanup
/area outputs
alertmanager: add missing statds/dogstastd metrics
/assign @Issif

alertmanager: add missing statds/dogstastd metrics

---

outputs/datadog.go

/kind cleanup
/area outputs
datadog: add missing statds/dogstastd metrics
/assign @Issif

datadog: add missing statds/dogstastd metrics

---

outputs/discord.go

/kind cleanup
/area outputs
discord: add missing statds/dogstastd metrics
/assign @Issif

discord: add missing statds/dogstastd metrics

---

outputs/elasticsearch.go

/kind cleanup
/area outputs
elasticsearch: add missing statds/dogstastd metrics
/assign @Issif

elasticsearch: add missing statds/dogstastd metrics

---

outputs/googlechat.go

/kind cleanup
/area outputs
googlechat: add missing statds/dogstastd metrics
/assign @Issif

googlechat: add missing statds/dogstastd metrics

---

outputs/nats.go
outputs/stan.go

/kind cleanup
/area outputs
nats: organize the nats code to be similar to others
related https://github.com/falcosecurity/falcosidekick/issues/144
/assign @Issif

nats: organize the nats code to be similar to others

---

outputs/azure.go

/kind cleanup
/area outputs
azure: add missing statds/dogstastd metrics
/assign @Issif

azure: add missing statds/dogstastd metrics

---

outputs/influxdb.go

/kind cleanup
/area outputs
influxdb: add missing statds/dogstastd metrics
/assign @Issif

influxdb: add missing statds/dogstastd metrics

---

outputs/opsgenie.go

/kind cleanup
/area outputs
opsgenie: add missing statds/dogstastd metrics
/assign @Issif

opsgenie: add missing statds/dogstastd metrics

---

outputs/loki.go

/kind cleanup
/area outputs
loki: add missing statds/dogstastd metrics
/assign @Issif

loki: add missing statds/dogstastd metrics

---

outputs/teams.go

/kind cleanup
/area outputs
teams: add missing statds/dogstastd metrics
/assign @Issif

teams: add missing statds/dogstastd metrics

---

OWNERS

I proposed in last community call to officially accept @cpanato as an official maintainer of `falcosidekick`. Everybody agrees, so this PR adds him into our beloved famiglia 😉 
N/A
Fixes #
N/A
Thank you @cpanato for your help with this project 🙏

add cpanato as official maintainer

---

outputs/mattermost.go

/kind cleanup
/area outputs
mattermost: add missing statds/dogstastd metrics
/assign @Issif

mattermost: add missing statds/dogstastd metrics

---

outputs/rocketchat.go

/kind cleanup
/area outputs
rocketchat: add missing statds/dogstastd metrics
/assign @Issif

rocketchat: add missing statds/dogstastd metrics

---

OWNERS

> /kind bug
> /kind design
> /area build
> /area config
> /area tests
Me and cpanato starting working almost at the same time. We been working for this project more than a month improving a lot.
I also contributed to chart, website and etc.
I want to contribute more as a maintainer.
Fixes #

Add KeisukeYamashita as maintainer

---

CHANGELOG.md

> /kind bug
> /kind design
/kind feature
/area build
> /area config
/area outputs
> /area tests
This PR updates the changelog for releasing `2.20.0`.
N/A
Fixes #

Prepare changelog for 2.20.0

---

outputs/webui.go

/kind bug
> /kind design
> /area build
> /area config
/area outputs
> /area tests
Add a missing space in log lines for `WebUI` output
N/A
Fixes #

fix missing space in webui log

---

CHANGELOG.md

> /kind bug
> /kind design
/kind feature
/area build
> /area config
> /area tests
Prepare the new release 2.21.0
Fixes #

prepare 2.21.0

---

Dockerfile

> /kind bug
/kind cleanup
> /kind design
/area build
> /area config
> /area tests
Upgrade Go to 1.16 and use smaller build images.
None.

Upgrade Go in Dockerfile and use smaller build image

---

.circleci/config.yml
.gitignore
.goreleaser.yml
Dockerfile
Makefile
outputs/aws.go

/kind feature
/area build
Add goreleaser for falcosidekick
Fixes #

add goreleaser

---

main.go
outputs/webui.go
types/types.go

> /kind bug
> /kind design
/kind feature
> /area build
> /area config
/area outputs
> /area tests
We're currently working on `v1.0.0` of [falcosidekick-ui](https://github.com/falcosecurity/falcosidekick-ui) with @fjogeleit. This PR prepares the new payload with an `UUID` by event and no more pushed stats (compute is made in UI backend now) 
N/A
Fixes #

prepare webui output for v1.0.0

---

OWNERS

Signed-off-by: Frank Jogeleit <frank.jogeleit@web.de>
> /kind bug
> /kind design
> /area build
/area config
> /area tests
Be able to review and approve falcosidekick-ui related PRs.
Fixes #

add fjogeleit to owners

---

CHANGELOG.md

> /kind bug
> /kind design
/kind feature
/area build
> /area config
> /area tests
This PR prepares release 2.22.0
Fixes #

prepare changelog for 2.22.0

---

.circleci/config.yml

/kind cleanup
/area build
circleci: run workflow when creating tags
ref: https://circleci.com/docs/2.0/configuration-reference/#tags
Fixes #

circleci: run workflow when creating tags

---

CHANGELOG.md

> /kind bug
/kind cleanup
> /kind design
> /area build
> /area config
> /area tests
I noticed the changelog had typo for dates and release 2.21.0 was missing. I fixed it.
Fixes #

fix changelog for last 2 releases

---

main.go
outputs/statsd.go

/kind bug
> /kind design
> /area build
> /area config
/area outputs
> /area tests
Init of DogstatsD client is broken.
#225 
Fixes #

fix statsd/dogstatsd: NewStatsdClient never initiated for Dogstatsd

---

README.md

> /kind bug
> /kind design
> /area build
> /area config
/area outputs
> /area tests
`RabbitMQ` is missing from list of available outputs. This PR fixes it.
Fixes #

add rabbitmq in list of available outputs

---

README.md

Signed-off-by: Leonardo Grasso <me@leonardograsso.com>
> /kind bug
> /kind design
> /area build
> /area config
> /area tests
Fixes #

docs(README.md): correct link

---

OWNERS

Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
I'm proposing myself as an approver and a reviewer to the project

proposing myself as an approver and a reviewer to the project

---

README.md

Fixed markdown typo in README

---

CHANGELOG.md
README.md

> /kind bug
> /kind design
> /area build
> /area config
/area outputs
> /area tests
fix missing entry in changelog of 2.23.0
Fixes #

add missing GCP functions in changelog of 2.23.0

---

CONTRIBUTING.md

Signed-off-by: Tom Kelley <distortedsignal@gmail.com>
> /kind bug
> /kind design
> /area build
> /area config
> /area tests
documentation?
I was really confused why my PR got tagged "dco-signoff: no", and I wanted to make sure that nobody else was confused like I was.
N/A

Add DCO explanation.

---

CHANGELOG.md

/kind bug
> /kind design
/area build
> /area config
> /area tests
This PR is a bug fix see #252 
Fixes #

prepare 2.23.1

---

README.md
config.go
config_example.yaml
handlers.go
main.go
outputs/grafana.go
stats.go
types/types.go

> /kind bug
> /kind design
/kind feature
> /area build
> /area config
/area outputs
> /area tests
This PR adds a new output, `Grafana` (annotations)
Fixes #

add grafana output

---

.circleci/config.yml

Signed-off-by: maxgio92 <massimiliano.giovagnoli.1992@gmail.com>
/kind bug
/area build
This PR includes the missing but required dependencies on the build and artifact publish job to AWS ECR.
NONE

ci: include required deps for build and push to ecr

---

CHANGELOG.md
README.md
go.sum

> /kind bug
> /kind design
/kind feature
/area build
> /area config
/area outputs
> /area tests
This PR is for release v2.24.0
Fixes #

prepare v2.24.0

---

Dockerfile

/kind cleanup
/kind feature
/area build
update base image to alpine 3.15, the current base image is old and have several CVEs
Fixes #

update base image to alpine 3.15

---

Makefile

/kind cleanup
/area build
- upgrade golangci-lint to 1.43.0
/assign @Issif @leogr 
Fixes #

upgrade golangci-lint to 1.43.0

---

.circleci/config.yml
go.mod

update Golang to 1.17.4
/kind feature
/area build
Fixes #

update Golang to 1.17.4

---

.circleci/config.yml

/kind bug
/kind cleanup
/area build
missed to update the command for the ecr job :( my bad
this fix the ecr job
Fixes #

ci: fix ci to use make to inject some variables

---

README.md

> /area build
> /area config
> /area tests
Fixes #

docs: Fix typo in README: "ecossytem"

---

CHANGELOG.md

/kind bug
> /kind design
/kind feature
/area build
/area config
/area outputs
/area tests
This is for the release of `2.25.0`
Changelog:
- New output: **Policy Report** ([PR#256](https://github.com/falcosecurity/falcosidekick/pull/256) thanks to [@anushkamittal20](https://github.com/anushkamittal20))
- New output: **Syslog** ([PR#272](https://github.com/falcosecurity/falcosidekick/pull/272) thanks to [@bdluca](https://github.com/bdluca))
- New output: **AWS Kinesis** …

prepare-2.25.0

---

.goreleaser.yml
go.sum

/kind cleanup
/area build
- sync go modules
- remove goreleaser proxy for now
Fixes #
/assign @Issif

Sync mod & remove goreleaser proxy for now

---

README.md
config_example.yaml
outputs/aws.go

/kind bug
> /kind design
> /area build
> /area config
/area outputs
> /area tests
When the Region for AWS is not set, the SDK wasn't able to create the session, with these changes, Sidekick will try to set the region thanks to the env vars or metadata.
#325 
Fixes #

try to get the Region for AWS with the env vars or metadata

---

README.md
config.go
config_example.yaml
outputs/loki.go
outputs/loki_test.go
outputs/utils.go
stats_prometheus.go
types/types.go

> /kind bug
> /kind design
/kind feature
> /area build
> /area config
/area outputs
> /area tests
This PR adds new settings, `loki.extralabels` and `prometheus.extralabels` which allow to set comma separated list of fields to use as labels additionally to `rule`, `source`, `priority`, `tags` and `custom_fields`
#324 
Fixes #

add settings for adding extra labels for loki and prometheu series

---

CHANGELOG.md

> /kind bug
> /kind design
/kind feature
> /area build
> /area config
/area outputs
> /area tests
Prepare v2.26.0
Fixes #

prepare 2.26.0

---

config.go
config_example.yaml
handlers.go
types/types.go

> /kind bug
> /kind design
/kind feature
> /area build
/area config
> /area tests
This PR introduces new fields that can be added to events, they use go template and `output_fields` values. See #329 for more details.
#329 
Fixes #

add templated fields

---

outputs/client_test.go

> /kind bug
/kind cleanup
> /kind design
> /area build
> /area config
/area outputs
> /area tests
remove ref to Sysdig
Fixes #

remove ref to Sysdig

---

handlers.go
outputs/policyreport.go

Signed-off-by: Frank Jogeleit <frank.jogeleit@lovoo.com>
> /kind bug
> /kind design
/kind feature
> /area build
> /area config
/area outputs
> /area tests
Improve the PolicyReport mapping by adding additional information from the k8saudit plugin if available.
* Add the Resource of an PolicyReportResult
* Add new Severity values *info* and *critical*
* Use minimumPriority as intended
Fixes #

Update PolicyReport mapping

---

README.md

Signed-off-by: Trevor Sullivan <trevor@trevorsullivan.net>
Signed-off-by: Trevor Sullivan <trevor@trevorsullivan.net>
> /kind bug
> /kind design
> /area build
> /area config
> /area tests
Fixes #

Add Tekton and KNative to README

---

config.go

/kind bug
> /kind design
> /area build
/area config
> /area tests
Add missing checkPriority
Fixes #

add missing checkPriority

---

CHANGELOG.md

> /kind bug
> /kind design
/kind feature
/area build
/area config
/area outputs
> /area tests
PR for 2.27.0 release
Fixes #

update changelog for 2.27.0

---

README.md

Signed-off-by: pandyamarut <pandyamarut@gmail.com>
documentation
Adds a full example Url to SLACK_WEBHOOKURL, currently it is incomple, it is just ~(ex:

add example for slack webhook url

---

.github/workflows/build-image.yml
.github/workflows/push-main.yml
.golangci.yml
main.go
outputs/policyreport.go

/kind bug
/area build
- fix missing GOPATH
/assign @leogr 
Fixes #

fix missing GOPATH

---

.github/workflows/push-main.yml

/kind cleanup
/area build
- add option to trigger manually  and update docker secret name
/assign @leogr 
Fixes #

add option to trigger manually and update docker secret name

---

README.md
config.go
config_example.yaml
handlers.go
types/types.go

> /kind bug
> /kind design
/kind feature
> /area build
> /area config
/area outputs
> /area tests
Add `bracketreplacer` setting. It allows to replace the brackets in output fields:
If `bracketreplacer = "_"`
```
proc.args[0]  -> proc.args_0
```
If `bracketreplacer = "."`
```
proc.args[0]  -> proc.args.0
```
Fixes #400 

add bracketreplacer setting

---

.github/workflows/release.yml

/kind bug
/kind cleanup
/area build
/area config
As per title. Probably didn't get updated since the GitHub Actions transition.
Fixes #

fix(gha): update dockerhub variable names for release job

---

outputs/alertmanager.go
outputs/alertmanager_test.go

> /kind bug
> /kind design
/kind feature
> /area build
> /area config
/area outputs
> /area tests
#477
Fixes #

alertmanager: add output in a description annotation too

---

.github/workflows/lint.yml

/kind cleanup
- update golanci-lint to v1.52
Fixes #

update golanci-lint to v1.52

---

README.md
config.go
config_example.yaml
outputs/smtp.go
types/types.go

/kind bug
> /kind design
> /area build
> /area config
> /area tests
Users faced these errors when they disable the auth mechanism for the  `smtp` output
```shell
2023/06/06 11:04:08 [ERROR] : SMTP - Send Mail failure : smtp: server doesn't support AUTH
2023/06/06 11:04:08 [ERROR] : SMTP - Send Mail failure : smtp: server doesn't support AUTH
2023/06/06 11:04:08 [ERROR] : SMTP - Send Mail failure : smtp: server doesn't support AUTH
```
I found it's related to the lib used to send the email, …

add TLS option for SMTP + rewrite the method to send the mails

---

README.md
config.go
config_example.yaml
handlers.go
main.go
outputs/openobserve.go
stats.go
types/types.go

> /kind bug
> /kind design
/kind feature
> /area build
> /area config
/area outputs
> /area tests
Add [OpenObserve](https://openobserve.ai) output
Fixes #

add OpenObserve output

---

outputs/kafka.go

/kind bug
> /kind design
> /area build
> /area config
/area outputs
> /area tests
Fix several missing returned errors
https://github.com/falcosecurity/falcosidekick/issues/572
Fixes #

fix missing returned errors

---

README.md

None.
Fix the broken link for the Dyntrace example image in the README.

docs(dynatrace): Fix typo in Dynatrace example image

---

outputs/cloudevents.go

/kind bug
> /kind design
> /area build
> /area config
/area outputs
> /area tests
#580 
Fixes #

fix bug with extension 'source'

---

README.md
handlers.go

/kind bug
> /kind design
> /area build
> /area config
/area outputs
> /area tests
See #611 
Fixes #

fix panic in prometheus when hostname field is missing

---

README.md

> /kind bug
> /kind design
> /area build
> /area config
> /area tests
Fixes #

add table of contents + fix missing link

---

go.mod
go.sum
handlers.go
stats_prometheus.go
stats_prometheus_test.go

> /kind bug
> /kind design
/kind feature
> /area build
> /area config
/area outputs
> /area tests
Fixes #

add source as label for prom metrics

---

docs/outputs/pagerduty.md

/kind bug
> /kind design
> /area build
> /area config
> /area tests
Fixes #

fix wrong env var for pagerduty output

---

README.md

> /kind bug
> /kind design
> /area build
/area config
> /area tests
Update the section about the installation
#704 
Fixes #

update the installation section

---

README.md

> /area build
> /area config
> /area tests
Fixes #
The link to the readme was pointing to wrong path.

Update README.md path to the correct one

---

outputs/client.go

/kind bug
> /kind design
> /area build
> /area config
/area outputs
> /area tests
Remove headers when the request to the output fails to avoid duplication
#780 
Fixes #

fix issue #780: duplicated headers

---

README.md

> /kind bug
/kind cleanup
> /kind design
> /area build
> /area config
> /area tests
Fixes #

docs(README.md): remove leftover

---

outputs/gcp.go

/kind bug
> /kind design
> /area build
> /area config
/area outputs
> /area tests
Checks more the result of the upload to GCP Storage
#809 
Fixes #

add more checks for the upload on GCP Storage

---

README.md
config.go
config_example.yaml
docs/outputs/talon.md
handlers.go
main.go
outputs/talon.go
stats.go
types/types.go

> /kind bug
> /kind design
/kind feature
> /area build
> /area config
/area outputs
> /area tests
Add [falco-talon](https://github.com/Falco-Talon/falco-talon) as new output
Fixes #

add Falco Talon output

---

docs/outputs/dynatrace.md

/kind bug
> /kind design
> /area build
> /area config
/area outputs
> /area tests
Fixes #

fix the docs for Dynatrace output

---

.goreleaser.yml

/kind bug
> /kind design
/area build
> /area config
> /area tests
goreleaser failed: https://github.com/falcosecurity/falcosidekick/actions/runs/9747381725/job/26900965743
Fixes #

specify goreleaser version

---

.github/dependabot.yml
.github/workflows/lint.yml
.github/workflows/release.yml

/kind cleanup
> /area build
> /area config
> /area tests
- updates for lint/goreleaser/dependabot
/assign @Issif 
Fixes #

updates for lint/goreleaser/dependabot

---

go.mod

/kind cleanup
/assign @Issif 
> /area build
> /area config
> /area tests
Fixes #

update go.mod to use toolchain 1.22.5

---

docs/outputs/datadog.md

The image had a broken link
> /kind bug
> /kind design
> /area build
> /area config
/area outputs
> /area tests
Fixes #

Update datadog.md to fix broken image

---

.github/dependabot.yml

remove labels that we dont use and generate  comments

---

CHANGELOG.md

> /kind bug
> /kind design
/kind feature
/area build
> /area config
/area outputs
> /area tests
Release v2.30.0
Fixes #

update the CHANGELOG.md for the v2.30.0

---

outputs/talon.go

/kind bug
/kind cleanup
> /kind design
> /area build
> /area config
/area outputs
> /area tests
-_-'
Fixes #

remove debug line -_-

---

outputs/policyreport.go

/kind bug
> /kind design
> /area build
> /area config
/area outputs
> /area tests
Fix the error when Falcosidekick tries to create a Cluster Policy Report:
```
2025/01/23 15:10:53 [ERROR] : PolicyReport - Can't Update the Cluster Policy Report falco-cluster-policy-report: resource name may not be empty
```
#1098 
Fixes #

fix the failing creation of the cluster policy report

---

docs/outputs/otlp_metrics.md
internal/pkg/utils/utils.go
main.go
outputs/cliq.go
outputs/cliq_test.go
outputs/teams.go
outputs/teams_test.go

/kind bug
> /kind design
> /area build
> /area config
/area outputs
> /area tests
I introduced a regression in #1102 for the logs, I used the wrong printer for the logs.
Fixes #

change the printer for the logs

---

CHANGELOG.md
docs/outputs/loki.md
docs/outputs/nats.md
docs/outputs/stan.md

/kind bug
> /kind design
> /area build
> /area config
/area outputs
> /area tests
Fixes #

prepare v2.31.1
